### ISSUE TITLE
Setting the defaultServiceId

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/telephony#54]
The TelephonyManager current has:

> attribute DOMString defaultServiceId

Implying that the defaultServiceId can be set. However, it does not define the rules for setting (can I set it to any string?). What happens if it's not a valid service id? etc. 

This should be set to readonly till we figure out the way to do it properly.

**Comment by zolkis** [comment]
The developer can list the available services via the serviceIds array, and set one of the values from there as defaultServiceId. There must be a way to set it. This is a synchronous set operation, since the telephony services do exist and must be enabled in order to be listed. However, it could also be considered an ansync operation, if we want to have some room for confirmation from the backends. Maybe a setDefaultService(id) method returning a Future and a readonly defaultServiceId is the best way to do it.

**Comment by marcoscaceres** [comment]
Yeah, that's what I was thinking too.

**Comment by marcoscaceres** [comment]
Ok, so lets do this:
1. make defaultServiceId readonly. 
2. add setDefaultService()
3. when the service changes, service change event is fired.

**Comment by zolkis** [comment]
Deal.

**Comment by marcoscaceres** [comment]
work in progress.
