### ISSUE TITLE
another way to create conferenceCall

### ISSUE THREAD

**Issue by hsinyi** [sysapps/telephony#87]
Hi all, sorry for jumping in. I review the current conferenceCall API and have some thoughts that I would like to share with you. :) 

In TelephonyCall.join(), we take an empty parameter. That means that 'join()' merges all the calls. The design could work well in the current cellular telephony services, because no more calls than an active call and a held call exist in a single device. But if we would like to consider flexibility and extensibility to address the case of more calls, eg. 1 active and 2 held ones, then this 'join()' method provides no options to merge with a specified existing call. It would be better to have a explicit parameter telling which call we are going to join. 

I would like to propose some changes, which are basically what mozilla has, and see how you think about this. Thanks :)

partial interface TelephonyManager {
  readonly attribute ConferenceCall conCall;
};

partial interface ConferenceCall {
  // Add a call to the callgroup. call2 must not be specified if the
  // ConferenceCall isn't empty.
  // If the ConferenceCall is empty both call and call2 must be specified,
  // and one of them must be in 'held' state and the other in
  // 'active' state.
  // Neither call or call2 can be in 'disconnected' state.
  void join (TelephonyCall participant1, optional TelephonyCall participant2);
  void split (TelephonyCall participantCall);
};

**Comment by zolkis** [comment]
We have discussed this on the F2F.

GSM TS 24.084 (e.g. http://www.etsi.org/deliver/etsi_ts/124000_124099/124084/04.00.00_60/ts_124084v040000p.pdf page 7) specifies join to merge all the calls of the subscriber, no matter how many of them, ie.e the semantics is 'join all calls of the subscriber'. So we cannot handpick any call to merge with another.

If there is a protocol where this is possible (please quote telephony specs) then right, we can add a new method for that, which would throw an error if used with protocols (telephony services) which don't support it.

The earlier (and now removed) optional parameter which was there for adding participants in VoIP calls, i.e. it would have no effect in CDMA and GSM, but only in protocols where one can add participants (SIP, XMPP). This was requested to be removed on the F2F in this version of the spec.

We went through the 3-way call vs GSM multiparty scenarios with Giri, and it seems that the current model works with both, with the remarks made in the specification.

**Comment by hsinyi** [comment]
Thanks for the comment, Zoltan.

Yes, I remember that we came to a conclusion that discarding .join(optional number), which isn't the one I'm proposing here. Here's difference: removed parameter is a 'number.' In the earlier case we shall dial out a new call with that number, then merging that in sequence. 

I know the current API works well with the current spec. And you are right, there's no cellular specification mentioning that specific case I said at this moment. Indeed, the spec says 'The mobile subscriber wishes all his calls to be connected together in a MultiParty call.' but it also says at the beginning "The served mobile subscriber A may initiate an active MultiParty call from an active call C and a held call B." And in current technology, we don't have calls more than two, an active and a held. That's why this proposal takes two parameters and works as well. 

However, just as I was proposing, I thought it could be a simple change to provide more extensibility to this API but still meet current spec.

**Comment by zolkis** [comment]
IMO we cannot make sure a join(call1, call2) can be implemented in cellular telephony services. Moreover, I don't see the API going that way in the future either. Once we have protocol support, as I said, we could add a new method.

Similarly, when we want SIP/XMPP conference, we will add a new method for that (e.g. addParticipant).

**Comment by zolkis** [comment]
One thing we could do: rename join() to createConference().

In cellular telephony services, the description will make clear this joins all calls. The participating TelephonyCall objects will be managed by the ConferenceCall, and will have their 'disconnect()' method available for GSM, but not available for CDMA (if we can do this nicer in the API, please suggest).

In SIP and XMPP services, 'createConference' would create a ConferenceCall object with new methods available: addParticipant and removeParticipant, which would not be present on cellular ConferenceCall objects.

This would give a cleaner evolution path towards supporting VoIP, rather than having separate methods for making conference calls for different telephony services.

Once again about @hsinyi 's proposal: since cellular is joining _all_ calls, and VoIP is working with participants as remote parties and not calls, I don't see any case when the parameters to join/createConference would be TelephonyCall objects. But if you can show telephony specs and real cases for that, I am open to take that into account.

@marcoscaceres could you please chime in with an opinion about this API (re)design with 'createConference'?

**Comment by hsinyi** [comment]
I don't have more specs. As I said, this proposal wants to provide more flexibility and extensibility, i.e.  leaving a possible way to merge with a specified call, while it still works for the current spec.

Another concept behind the proposal that I didn't mention explicitly is that I hope it could also help resolve ambiguity of having separate methods for making conference calls for different telephony services, as Zoltan has mentioned, though we agree the scope of this API restricted to cellular network at this moment. That's why there's a default TelephonyManager::conCall, so that we don't have different ways of creating it. So, Zoltan's redesign, the idea of createConference(), looks great IMHO.

**Comment by marcoscaceres** [comment]
I'm in favor of @zolkis proposal, but tying the availability of methods based on protocols is not ideal. I suggest when disconnect() method is invoked, we either throw a `NotSupported` error or, in the case we use future, just resolve to an error. The same applies to `addParticipant` and `removeParticipant`.

**Comment by zolkis** [comment]
Thanks Hsin-Yi, then will make this API change to use createConference() on the TelephonyCall although it should work at TelephonyService level (which is not explicitly visible in this API). 

Marcos, thanks for the comment, I will do then the error management way for now. But for the long term do we expect that when we introduce VoIP/LTE support, the 'addParticipant' and 'removeParticipant' methods should be there even for cellular protocols where we know it is not supported?

I'd like to understand more reasoning why the availability of methods based on protocol is not ideal.

**Comment by zolkis** [comment]
For instance, when we will support telephony services like call barring, supplementary services etc, only some of the telephony services will have it. For instance:

<pre>
[NoInterfaceObject]
interface TelephonyService : EventTarget {
    readonly attribute DOMString serviceId;
    attribute DOMString displayName; // to be shown in a UI
    readonly attribute boolean  enabled;
    readonly attribute DOMString provider;
    readonly attribute DOMString type;
    readonly attribute DOMString[] emergencyNumbers;
    readonly TelephonyCall[] calls;
    attribute EventHandler oncallschanged;
    TelephonyCall dial(DOMString remoteParty, optional DialParams params);
    Promise sendTones(DOMString tones, optional ToneParams params);
    Promise startTone(DOMString tone);
    Promise stopTone();
    Promise setEnabled(boolean enabled);
    //...
};
interface CellularService : TelephonyService {
    // telephony service (provider + SIM + modem) related interfaces
    // if an interface is not supported, the property is null
    readonly attribute SimInfo?                 siminfo; // IMSI, MCC, MNC, ...
    readonly attribute SimSettings?          simsettings; //PIN, PUK, ...
    readonly attribute SimToolkit?             simtoolkit;
    readonly attribute TelephonyNetwork? network;
    readonly attribute CallForwarding?      forwarding;
    readonly attribute CallBarring?            barring;
    readonly attribute CallMeters?            meters; // costs
    // further extensible
};
</pre>

So it would be used like

<pre>
if(service.siminfo) {
    // use service.siminfo.imsi
}
</pre>

**Comment by marcoscaceres** [comment]
It would not be ideal to have different return types for the `createConference()` method based on different protocols (because it then gets confusing as you need to check what protocol the call is using). With the current proposal that removes methods, the way to check this would be to "duck type": `if("addParticipant" in confcall){...`. That's not great. 

There is also no way to express this in WebIDL either (without defining a new interface for a particular protocol - or a generic type for protocols that support this kind of participant management).

**Comment by zolkis** [comment]
Thanks, Marcos. So we'd rather use a union of all possible interfaces, and they would work or throw error depending on the context. Not perfect either, and the developer would have to check for the error instead of the existence of the method, but let's start with that.

Yes, with WebIDL we'd need to define different kinds of ConferenceCall objects. Which would reflect the reality, actually :)
