### ISSUE TITLE
CallDirection: Transitioning between missed-new and missed

### ISSUE THREAD

**Issue by efullea** [sysapps/telephony#94]
'direction' attribute in the CallHistoryEntry Interface is readonly. How is it supposed to change from 'missed-new' to 'missed' when the missed call entry is presented to the user and thus no longer new?

**Comment by zolkis** [comment]
We did not include data API in this version, only the description of what is to be stored. Should we include call history management?

**Comment by efullea** [comment]
I don't think we need to include call history management. It looks wierd though that all attributes can be set by the system with exception of CallDirection to value 'missed', which AFAIU is the result of an app displaying to the user the record of a call with CallDirection with value 'missed-new'. I propose we merge 'missed' and 'missed-new' into a single value 'missed'. Each app would manage internally which of the missed calls are new and which not.

**Comment by zolkis** [comment]
The condition 'missed-new' needs to survive reboots. It has to be in the DB. If any app sees it, it will lose the 'new' flag.

**Comment by efullea** [comment]
If we assume that is the use case, then we can either remove the readonly from the 'duration' attribute or remove the  CallHistoryEntry altogether. Otherwise the API is not consistent.

**Comment by zolkis** [comment]
Duration is set by the implementation. I don't understand what you mean.

**Comment by efullea** [comment]
Sorry I meant 'direction'

**Comment by zolkis** [comment]
CallHistoryEntry is a data format spec, listing the minimum amount of information to be saved by implementations/dialers to call history. It is up the the dialers/implementations on how to store and access it. 

So what is the value? Compliance with eventual future changes. Implementations do need this information, and someone needs to standardize it.

I don't think it is broken because one cannot change it from this API. It specifies what data needs to be there, and some other (private, or public) API will access/search/modify it.

**Comment by efullea** [comment]
OK, but it would be good to have a Note explaining why this is included in here and why it is non-normative, so basically you last comment to the thread.

**Comment by zolkis** [comment]
OK, will do that. After the PR is made, please check it and close the issue yourself when you think it's handled.
